# Generated by Django 4.0.2 on 2022-03-10 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_ipaddress_article_hits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='hits',
        ),
    ]
