# Generated by Django 4.0.2 on 2022-03-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_articlehit_article_hits_articlehit_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits', through='blog.ArticleHit', to='blog.IpAddress', verbose_name='بازدید ها'),
        ),
    ]
